### ISSUE TITLE
hc_add_series_df(df) returns silently failed highchart if sum(colnames(df)=="series")>=1 

### ISSUE THREAD

**Issue by martinjhnhadley** [jbkunst/highcharter#241]
If you provide `hc_add_series_df` with a data.frame (or tibble) with a colname equal to "series" a viewer will successfully be spawned but will not contain a highchart.

Example:

```r
library(dplyr)
library(highcharter)
n <- 100
df <- data_frame(
  x = rnorm(n),
  y = x * 2 + rnorm(n),
  w =  x^2,
  series = sample(c("a","b","c","eee"), 100, replace = TRUE)
)

highchart() %>%
  hc_add_series_df(data = df, 
                   type = "point", 
                   x = x, 
                   y = y
                   name = series
                   )
```

Output from console in browser:

```
Uncaught TypeError: Array.prototype.forEach called on null or undefined
    at forEach (native)
    at n (http://localhost:30593/session/viewhtml194c4550381d/lib/highcharts-4.2.4/highstock.js:26:336)
    at c.updateParallelArrays (http://localhost:30593/session/viewhtml194c4550381d/lib/highcharts-4.2.4/highstock.js:245:296)
    at c.setData (http://localhost:30593/session/viewhtml194c4550381d/lib/highcharts-4.2.4/highstock.js:250:282)
    at c.init (http://localhost:30593/session/viewhtml194c4550381d/lib/highcharts-4.2.4/highstock.js:244:285)
    at c.<anonymous> (http://localhost:30593/session/viewhtml194c4550381d/lib/highcharts-4.2.4/highstock.js:343:173)
    at c.a.(anonymous function) (http://localhost:30593/session/viewhtml194c4550381d/lib/highcharts-4.2.4/highstock.js:22:303)
    at c.ia.init (http://localhost:30593/session/viewhtml194c4550381d/lib/highcharts-4.2.4/highstock.js:430:369)
    at z.Chart.initSeries (http://localhost:30593/session/viewhtml194c4550381d/lib/highcharts-4.2.4/highstock.js:214:372)
    at http://localhost:30593/session/viewhtml194c4550381d/lib/highcharts-4.2.4/highstock.js:236:343
```

It might well say somewhere in the documentation that colnames should NOT be series - which I think is reasonable but I missed this.

**Comment by jbkunst** [comment]
Hi @martinjhnhadley 

I missed too, I didn't know about this issue. I will fix this. Thanks.

`hc_add_series_df` will be deprecated in the next version. The new sintax when the data object is data frame is:

```
highchart() %>% 
  hc_add_series(df, type = "point", hcaes(x = x, y = w, name = seriess))
```

**Comment by jbkunst** [comment]
Hi @martinjhnhadley 

The issue was fixed. You can use:

```r
hchart(df, "point", hcaes(x, y, name = series))

highchart() %>% 
  hc_add_series(df, "point", hcaes(x, y))

highchart() %>% 
  hc_add_series(df, "point", hcaes(x, y, name = series))
```

Not sure if there are other reserved names ;).  Thanks for report this.

Regards,

**Comment by martinjhnhadley** [comment]
That's awesome - thanks!

I should ask somewhere else, maybe, but until the new version hits CRAN I've been using the following to smuggle additional data into charts for tooltips etc... does hcaes allow similar data smuggling?

```r
## Convert df to smuggle data
df_to_hc_lists <- function(df) {
  
  if(!all(c("x","y") %in% colnames(df))){
    stop("Conversion to lists requires x, y columns")
  }
  
  output_list <- list()
  
  for (row in 1:nrow(df)) {
    output_list[[row]] <-
      # append(setNames(unlist(df[row,], use.names = F), c("x", "y", "myData")),
      #        c("size" = 1), after = 2) %>%
      # as.list()
      append(df[row,],list(z = 1)) # non-zero size
  } 
  output_list
}
## sample data
df <- data.frame(x = 1:5,
                 y = 5:9,
                 myData = letters[1:5])
## chart
highchart() %>%
  hc_add_series(
    data = df_to_3d_lists_2(df),
    type = "bubble",
    name = "Concordant (Local)",
    color = rgb(165, 15, 21, 0.9, max = 255),
    marker = list(fillOpacity = 0.7)
  ) %>%
  hc_tooltip( ## can access the data smuggled into the series
    formatter = JS(
      "function(){
      console.log(this);
      return '<b>' + this.series.name + '</b>' + 
      '<br/>' +
      '<b>myData: </b>' + this.point.myData +
      '<br/>' +
      '<b>R1: </b>' + this.x +
      '<br/>' +
      '<b>R2: </b>' + this.y;}"
    )
  )
```

**Comment by jbkunst** [comment]
You dont need the `df_to_hc_lists`,

First, you can do the same with `list_parse`, this transform a data frame into a list where every item in the list is a row of the original data frame, but again `df_to_hc_lists` neither `list_parse` are necessary.

```r
# compare
df_to_hc_lists(df)
list_parse(df)
```
Here It's better use  `hc_add_series` (hc_add_series.data.frame) with basically do:
- Take `hcaes` arguments to rename the columns, so you can have a data frame with `xvar` and `ycolumn` colums and use `hcaes(x = xvar, y = ycolumn)` . If `hcaes` is not given the function go to the next step, in your example you can omit this step because you have columns with `x`  and `y` names.
- Parse the data (for highcharts), same you do with `df_to_hc_lists`
- All rest of colums are passed to highcharts object so you can use in the tooltip.

```r
df <- data.frame(xvar = 1:5, yvar = 5:9, myData = letters[1:5])

highchart() %>%
  hc_add_series(data = df, type = "bubble", hcaes(x = xvar, y = yvar))
```

And you can use the `tooltip_table` helper to make tooltips as table given name and accessors (like `{this.x}` or `{point.y}`):

```r
x <- c("myData:", "R1", "R2")
y <- c("{point.myData}", "{point.x} UDS", "{point.y} $")

tltip_tmp <- tooltip_table(x, y)
> cat(tltip_tmp)
<table>
  <tr>
    <th>myData:</th>
    <td>{point.myData}</td>
  </tr>
  <tr>
    <th>R1</th>
    <td>{point.x} UDS</td>
  </tr>
  <tr>
    <th>R2</th>
    <td>{point.y} $</td>
  </tr>
</table>

highchart() %>%
  hc_add_series(data = df, type = "bubble", hcaes(x = xvar, y = yvar)) %>%
  hc_tooltip(pointFormat = tltip_tmp, useHTML = TRUE)
```

Finally, take a look to https://cran.r-project.org/web/packages/highcharter/vignettes/charting-data-frames.html ;)

Hope I was clear :grimacing:

**Comment by martinjhnhadley** [comment]
That was very clear - really looking forward to using it! Hadn't realised 0.5.0 hit CRAN already, I'm going to update for all the goodness right now 😃
